language: php

php:
  - '7.4'

dist: trusty

sudo: false

env:
  global:
    - setup=stable

services:
  - mysql

before_install:
  - travis_retry composer self-update

install:
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --prefer-stable --no-interaction --no-suggest; fi
  - if [[ $setup = 'normal' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS supplier;'
  - mysql -u root --password="" < tests/travis.sql
  - composer install
  - php artisan key:generate


cache:
  directories:
    - $HOME/.composer/cache

after_success:
  - php artisan -V
notifications:
 email: omar78701@gmail.com
